### PR TITLE
fix: filename from config on disabled /imagine

### PR DESCRIPTION
**Pull request by HeySlava**

### CODE REVIEW

**Comment by nalgeon** [comment]
What is the reason for `{config.imagine or False}`?

**Comment by HeySlava** [comment]
This is how my `/version` looks like

```
...

AI information:
- model: gpt-3.5-turbo
- history depth: 10
- imagine: None
- shortcuts: bugfix, proofread, summarize, translate, eng
```

I think it's better to have `imagine: False` or something like `imagine: disabled`

**Comment by nalgeon** [comment]
What is your version and what is the value of the `imagine` property in the `config.yml`?

**Comment by HeySlava** [comment]
Version: 125

I do not have property `imagine`

**Comment by nalgeon** [comment]
I don't think so. More likely is that you have `imagine: null` in your `config.yml`. Please check this.

**Comment by HeySlava** [comment]
I was wrong.  Currently, I can't reproduce that behavior.

Default value is True, which is surprising
image


image

**Comment by nalgeon** [comment]
The default value for `imagine` is `True`. That's correct.

**Comment by nalgeon** [comment]
You can revert the `imagine` changes, and I'll merge the PR.

**Comment by nalgeon** [comment]
Thanks!

**Pull request merged**
