### PR TITLE
Allow building docker image to not 64bit targets

### PR DESCRIPTION
**Pull request by Self-Perfection**
tiktoken dependency [comes precompiled](https://pypi.org/project/tiktoken/#files) only for 64bit targets
On other targets we need to compile it with rust.

------
For the context. At my setup original docker image used 3% of RAM and 0.06% of available CPU power. So it makes total sense to reduce RAM consumption at probable cost of extra CPU usage.

Just replacing `python:3.11-alpine` with `docker.io/i386/python:3.11-alpine` in FROM clause was not enough, I had to add rust. Eventually I succeeded: RAM usage reduced by 30% with no significant change of CPU usage.

Unfortunately though installing cargo and rust and recimpiling tiktoken inflates resulting image up to 1.2 GiB.

### CODE REVIEW

**Comment by nalgeon** [comment]
Sorry, but I would rather stick to 64 bit targets and not install rust etc.

**Comment by Self-Perfection** [comment]
Please check my proposed change.

It installs cargo & rust **only** for non 64bit targets, for 64bit targets it is effectively a noop.

What are the downsides? Except of making Dockerfile more complex.

**Comment by nalgeon** [comment]
But the container itself is built on the 64-bit image `python:3.11-alpine`. What's the point of this PR then?

**Comment by Self-Perfection** [comment]
Well I am not quite familiar with different architectures support in Docker but I assume running `docker build` should automatically select proper base image with host architecture. This is possible because `python:3.11-alpine` is a multiplatform image:
```
$ podman manifest inspect python:3.11-alpine | grep architecture
                "architecture": "amd64",
                "architecture": "arm",
                "architecture": "arm",
                "architecture": "arm64",
                "architecture": "386",
                "architecture": "ppc64le",
                "architecture": "s390x",
```

Therefore  for instance running `docker build` on Raspberry Pi would work if host OS is for arm64 even though. But it would fail on `pip3 install -r requirements.txt` stage on 32bit arm OS without this PR.

This is just a theory though, I have not tested it. Your question actually led me to the rabbit and I have not reached the bottom yet.

**Comment by Self-Perfection** [comment]
Yep, I was correct. I have tested in container with Debian i686. Using `python:3.11-alpine` on such OS downloads i686 version:

```
root@debian-12-i386-container:~/pokitoki# docker run --rm python:3.11-alpine cat /etc/apk/arch
x86
```

And build from HEAD fails but succeeds with my patch.

**Comment by nalgeon** [comment]
I see. Thanks a lot for the explanation!

**Pull request merged**
